### ISSUE TITLE
add new Command for `add Environment variable` to Deployment / DeploymentConfig

### ISSUE THREAD

**Issue by jstrachan** [gorkem/vscode-k8s#8]
which would then add this to the YAML file (creating any missing structs along the way)...
```yaml
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: FIXME
        env:
        - name: SOME_NAME
          value: SOME_VALUE
```
