### ISSUE TITLE
add a few Commands to create new files (e.g. Deployment, DeploymentConfig, Service, Route, ConfigMap, PVC)

### ISSUE THREAD

**Issue by jstrachan** [gorkem/vscode-k8s#9]
It'd be nice to have a little 'new kubernetes file' wizard that lets you pick from these kinds:

* Deployment
* DeploymentConfig
* Service
* Route
* ConfigMap
* PVC

then we could pre-fill in a few values (e.g. the `metadata.name` could default to the file name (without the `.yml` extension).

e.g. the generated Deployment might look like:
```yaml
metadata:
  name: ${FILE_NAME_WITHOUT_EXTENSION}
  labels:
    app: ${FILE_NAME_WITHOUT_EXTENSION}
    version: 1.0.0
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: main
```
